version: '3'
services:
  amqp:                                                      
    image: "rabbitmq:3-management"
    ports:                                                  
      - "5671:5671"                                          
      - "5672:5672"                                          
    expose:                                                
      - "5672"                                             
    healthcheck:                                           
      test: ["CMD", "curl", "-f", "http://localhost:5672"] 
      interval: 30s                                        
      timeout: 10s                                         
      retries: 5                                            
  node:
    build: .
    command: npm start
    restart: unless-stopped
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    #ports:         
      #- "3000:3030" usata per accedere direttamente a nodejs, disabilitata poichè usiamo nginx come load balancer
    expose:
      - 3030
    depends_on:
      - db
      - amqp
  node2:
    build: .
    command: npm start
    restart: unless-stopped
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    expose:
      - 3030
    depends_on:
      - db
      - amqp
  node-chat: # node image for chat server
    build:
      context: chat/
      dockerfile: Dockerfile
    command: node chat/chat-server.js
    restart: unless-stopped
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "1337:1337"
    expose:
      - 1337

  ngix:
    image: "nginx:latest"
    volumes:
      #- ./static:/usr/share/nginx/html:ro     # per accesso senza configurazione
      - ./static:/var/www
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/conf.d:/etc/nginx/conf.d
      - ./conf/keys:/etc/nginx/keys
    ports:
      - "8080:80"
      - "4443:443"
    expose:
      - 80
      - 443
    depends_on:
      - node    
  db:
    image: "couchdb"
    hostname: couchdb.local
    volumes:
      - ./conf/couchdb:/etc/default.d
    environment:
      COUCHDB_DEV_INIT: 'true'
      COUCHDB_ADMIN_USER: admin
      COUCHDB_ADMIN_PASS: secret
    ports:           
      - 5984:5984
    expose:
      - 5984
