version: '3'
services:
  node:
    image: fcolasante/sundaynode:1.0.1
    command: npm start
    ports:         
      - "3000:3030"
    depends_on:
      - db
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      #restart_policy:
        #condition: on-failure
  # ngix:
  #   image: "nginx:latest"
  #   volumes:
  #     #- ./static:/usr/share/nginx/html:ro     # per accesso senza configurazione
  #     - ./static:/var/www
  #     - ./conf/nginx.conf:/etc/nginx/nginx.conf
  #     - ./conf/conf.d:/etc/nginx/conf.d
  #     - ./conf/keys:/etc/nginx/keys
  #   ports:
  #     - "8080:80"
  #     - "4443:443"
  #   depends_on:
  #     - node    
  db:
    image: "couchdb"
    hostname: couchdb.local
    ports:           
      - 5984:5984
    networks:
      - internal
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "9000:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - internal
networks:
  internal:
    driver: overlay